# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sonic_interface_enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ywrapper_pb2 as ywrapper__pb2
import yext_pb2 as yext__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sonic_interface_enums.proto',
  package='openconfig',
  syntax='proto3',
  serialized_options=b'\n\025com.nocsys.openconfig',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bsonic_interface_enums.proto\x12\nopenconfig\x1a\x0eywrapper.proto\x1a\nyext.proto*\x8e\x01\n\x16SonicInterfaceIpFamily\x12 \n\x1cSONICINTERFACEIPFAMILY_UNSET\x10\x00\x12(\n\x1bSONICINTERFACEIPFAMILY_IPv4\x10\x01\x1a\x07\x82\x41\x04IPv4\x12(\n\x1bSONICINTERFACEIPFAMILY_IPv6\x10\x02\x1a\x07\x82\x41\x04IPv6*\x82\x01\n\x14SonicPortAdminStatus\x12\x1e\n\x1aSONICPORTADMINSTATUS_UNSET\x10\x00\x12\"\n\x17SONICPORTADMINSTATUS_up\x10\x01\x1a\x05\x82\x41\x02up\x12&\n\x19SONICPORTADMINSTATUS_down\x10\x02\x1a\x07\x82\x41\x04\x64ownB\x17\n\x15\x63om.nocsys.openconfigb\x06proto3'
  ,
  dependencies=[ywrapper__pb2.DESCRIPTOR,yext__pb2.DESCRIPTOR,])

_SONICINTERFACEIPFAMILY = _descriptor.EnumDescriptor(
  name='SonicInterfaceIpFamily',
  full_name='openconfig.SonicInterfaceIpFamily',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SONICINTERFACEIPFAMILY_UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICINTERFACEIPFAMILY_IPv4', index=1, number=1,
      serialized_options=b'\202A\004IPv4',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICINTERFACEIPFAMILY_IPv6', index=2, number=2,
      serialized_options=b'\202A\004IPv6',
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=72,
  serialized_end=214,
)
_sym_db.RegisterEnumDescriptor(_SONICINTERFACEIPFAMILY)

SonicInterfaceIpFamily = enum_type_wrapper.EnumTypeWrapper(_SONICINTERFACEIPFAMILY)
_SONICPORTADMINSTATUS = _descriptor.EnumDescriptor(
  name='SonicPortAdminStatus',
  full_name='openconfig.SonicPortAdminStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SONICPORTADMINSTATUS_UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICPORTADMINSTATUS_up', index=1, number=1,
      serialized_options=b'\202A\002up',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICPORTADMINSTATUS_down', index=2, number=2,
      serialized_options=b'\202A\004down',
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=217,
  serialized_end=347,
)
_sym_db.RegisterEnumDescriptor(_SONICPORTADMINSTATUS)

SonicPortAdminStatus = enum_type_wrapper.EnumTypeWrapper(_SONICPORTADMINSTATUS)
SONICINTERFACEIPFAMILY_UNSET = 0
SONICINTERFACEIPFAMILY_IPv4 = 1
SONICINTERFACEIPFAMILY_IPv6 = 2
SONICPORTADMINSTATUS_UNSET = 0
SONICPORTADMINSTATUS_up = 1
SONICPORTADMINSTATUS_down = 2


DESCRIPTOR.enum_types_by_name['SonicInterfaceIpFamily'] = _SONICINTERFACEIPFAMILY
DESCRIPTOR.enum_types_by_name['SonicPortAdminStatus'] = _SONICPORTADMINSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
_SONICINTERFACEIPFAMILY.values_by_name["SONICINTERFACEIPFAMILY_IPv4"]._options = None
_SONICINTERFACEIPFAMILY.values_by_name["SONICINTERFACEIPFAMILY_IPv6"]._options = None
_SONICPORTADMINSTATUS.values_by_name["SONICPORTADMINSTATUS_up"]._options = None
_SONICPORTADMINSTATUS.values_by_name["SONICPORTADMINSTATUS_down"]._options = None
# @@protoc_insertion_point(module_scope)
