# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sonic_portchannel_enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ywrapper_pb2 as ywrapper__pb2
import yext_pb2 as yext__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sonic_portchannel_enums.proto',
  package='openconfig',
  syntax='proto3',
  serialized_options=b'\n\025com.nocsys.openconfig',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dsonic_portchannel_enums.proto\x12\nopenconfig\x1a\x0eywrapper.proto\x1a\nyext.proto*\x82\x01\n\x14SonicPortAdminStatus\x12\x1e\n\x1aSONICPORTADMINSTATUS_UNSET\x10\x00\x12\"\n\x17SONICPORTADMINSTATUS_up\x10\x01\x1a\x05\x82\x41\x02up\x12&\n\x19SONICPORTADMINSTATUS_down\x10\x02\x1a\x07\x82\x41\x04\x64own*\x9e\x01\n\x1bSonicPortchannelAdminStatus\x12%\n!SONICPORTCHANNELADMINSTATUS_UNSET\x10\x00\x12)\n\x1eSONICPORTCHANNELADMINSTATUS_up\x10\x01\x1a\x05\x82\x41\x02up\x12-\n SONICPORTCHANNELADMINSTATUS_down\x10\x02\x1a\x07\x82\x41\x04\x64ownB\x17\n\x15\x63om.nocsys.openconfigb\x06proto3'
  ,
  dependencies=[ywrapper__pb2.DESCRIPTOR,yext__pb2.DESCRIPTOR,])

_SONICPORTADMINSTATUS = _descriptor.EnumDescriptor(
  name='SonicPortAdminStatus',
  full_name='openconfig.SonicPortAdminStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SONICPORTADMINSTATUS_UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICPORTADMINSTATUS_up', index=1, number=1,
      serialized_options=b'\202A\002up',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICPORTADMINSTATUS_down', index=2, number=2,
      serialized_options=b'\202A\004down',
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=74,
  serialized_end=204,
)
_sym_db.RegisterEnumDescriptor(_SONICPORTADMINSTATUS)

SonicPortAdminStatus = enum_type_wrapper.EnumTypeWrapper(_SONICPORTADMINSTATUS)
_SONICPORTCHANNELADMINSTATUS = _descriptor.EnumDescriptor(
  name='SonicPortchannelAdminStatus',
  full_name='openconfig.SonicPortchannelAdminStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SONICPORTCHANNELADMINSTATUS_UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICPORTCHANNELADMINSTATUS_up', index=1, number=1,
      serialized_options=b'\202A\002up',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICPORTCHANNELADMINSTATUS_down', index=2, number=2,
      serialized_options=b'\202A\004down',
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=207,
  serialized_end=365,
)
_sym_db.RegisterEnumDescriptor(_SONICPORTCHANNELADMINSTATUS)

SonicPortchannelAdminStatus = enum_type_wrapper.EnumTypeWrapper(_SONICPORTCHANNELADMINSTATUS)
SONICPORTADMINSTATUS_UNSET = 0
SONICPORTADMINSTATUS_up = 1
SONICPORTADMINSTATUS_down = 2
SONICPORTCHANNELADMINSTATUS_UNSET = 0
SONICPORTCHANNELADMINSTATUS_up = 1
SONICPORTCHANNELADMINSTATUS_down = 2


DESCRIPTOR.enum_types_by_name['SonicPortAdminStatus'] = _SONICPORTADMINSTATUS
DESCRIPTOR.enum_types_by_name['SonicPortchannelAdminStatus'] = _SONICPORTCHANNELADMINSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
_SONICPORTADMINSTATUS.values_by_name["SONICPORTADMINSTATUS_up"]._options = None
_SONICPORTADMINSTATUS.values_by_name["SONICPORTADMINSTATUS_down"]._options = None
_SONICPORTCHANNELADMINSTATUS.values_by_name["SONICPORTCHANNELADMINSTATUS_up"]._options = None
_SONICPORTCHANNELADMINSTATUS.values_by_name["SONICPORTCHANNELADMINSTATUS_down"]._options = None
# @@protoc_insertion_point(module_scope)
