# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sonic_loopback_interface_enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ywrapper_pb2 as ywrapper__pb2
import yext_pb2 as yext__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sonic_loopback_interface_enums.proto',
  package='openconfig',
  syntax='proto3',
  serialized_options=b'\n\025com.nocsys.openconfig',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$sonic_loopback_interface_enums.proto\x12\nopenconfig\x1a\x0eywrapper.proto\x1a\nyext.proto*\xae\x01\n\x1eSonicLoopbackInterfaceIpFamily\x12(\n$SONICLOOPBACKINTERFACEIPFAMILY_UNSET\x10\x00\x12\x30\n#SONICLOOPBACKINTERFACEIPFAMILY_IPv4\x10\x01\x1a\x07\x82\x41\x04IPv4\x12\x30\n#SONICLOOPBACKINTERFACEIPFAMILY_IPv6\x10\x02\x1a\x07\x82\x41\x04IPv6B\x17\n\x15\x63om.nocsys.openconfigb\x06proto3'
  ,
  dependencies=[ywrapper__pb2.DESCRIPTOR,yext__pb2.DESCRIPTOR,])

_SONICLOOPBACKINTERFACEIPFAMILY = _descriptor.EnumDescriptor(
  name='SonicLoopbackInterfaceIpFamily',
  full_name='openconfig.SonicLoopbackInterfaceIpFamily',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SONICLOOPBACKINTERFACEIPFAMILY_UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICLOOPBACKINTERFACEIPFAMILY_IPv4', index=1, number=1,
      serialized_options=b'\202A\004IPv4',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICLOOPBACKINTERFACEIPFAMILY_IPv6', index=2, number=2,
      serialized_options=b'\202A\004IPv6',
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=81,
  serialized_end=255,
)
_sym_db.RegisterEnumDescriptor(_SONICLOOPBACKINTERFACEIPFAMILY)

SonicLoopbackInterfaceIpFamily = enum_type_wrapper.EnumTypeWrapper(_SONICLOOPBACKINTERFACEIPFAMILY)
SONICLOOPBACKINTERFACEIPFAMILY_UNSET = 0
SONICLOOPBACKINTERFACEIPFAMILY_IPv4 = 1
SONICLOOPBACKINTERFACEIPFAMILY_IPv6 = 2


DESCRIPTOR.enum_types_by_name['SonicLoopbackInterfaceIpFamily'] = _SONICLOOPBACKINTERFACEIPFAMILY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
_SONICLOOPBACKINTERFACEIPFAMILY.values_by_name["SONICLOOPBACKINTERFACEIPFAMILY_IPv4"]._options = None
_SONICLOOPBACKINTERFACEIPFAMILY.values_by_name["SONICLOOPBACKINTERFACEIPFAMILY_IPv6"]._options = None
# @@protoc_insertion_point(module_scope)
