# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sonic_portchannel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ywrapper_pb2 as ywrapper__pb2
import yext_pb2 as yext__pb2
import sonic_acl_enums_pb2 as sonic__acl__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sonic_portchannel.proto',
  package='openconfig',
  syntax='proto3',
  serialized_options=b'\n\025com.nocsys.openconfig',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17sonic_portchannel.proto\x12\nopenconfig\x1a\x0eywrapper.proto\x1a\nyext.proto\x1a\x15sonic_acl_enums.proto\"\x98\x08\n\x10SonicPortchannel\x12\x63\n\x0bportchannel\x18\xf6\xe7\xb8\x11 \x01(\x0b\x32(.openconfig.SonicPortchannel.PortchannelB!\x82\x41\x1e/sonic-portchannel/portchannel\x1a\x9e\x07\n\x0bPortchannel\x12\x8c\x01\n\x10portchannel_list\x18\xaa\xaa\xcb\x38 \x03(\x0b\x32;.openconfig.SonicPortchannel.Portchannel.PortchannelListKeyB2\x82\x41//sonic-portchannel/portchannel/portchannel-list\x1a\xb5\x04\n\x0fPortchannelList\x12\x82\x01\n\x0c\x61\x64min_status\x18\x8d\x9d\xf6\x89\x01 \x01(\x0e\x32\'.openconfig.SonicPortchannelAdminStatusB?\x82\x41</sonic-portchannel/portchannel/portchannel-list/admin-status\x12n\n\x0b\x64\x65scription\x18\xad\xbc\xbb\xe9\x01 \x01(\x0b\x32\x15.ywrapper.StringValueB>\x82\x41;/sonic-portchannel/portchannel/portchannel-list/description\x12\x66\n\x07members\x18\xd2\xdb\xa0\xba\x01 \x03(\x0b\x32\x15.ywrapper.StringValueB:\x82\x41\x37/sonic-portchannel/portchannel/portchannel-list/members\x12g\n\tmin_links\x18\xcb\x8c\xfa\x32 \x01(\x0b\x32\x13.ywrapper.UintValueB<\x82\x41\x39/sonic-portchannel/portchannel/portchannel-list/min-links\x12\\\n\x03mtu\x18\xef\x92\xdd\xfb\x01 \x01(\x0b\x32\x13.ywrapper.UintValueB6\x82\x41\x33/sonic-portchannel/portchannel/portchannel-list/mtu\x1a\xc7\x01\n\x12PortchannelListKey\x12]\n\x10portchannel_name\x18\x01 \x01(\tBC\x82\x41@/sonic-portchannel/portchannel/portchannel-list/portchannel-name\x12R\n\x10portchannel_list\x18\x02 \x01(\x0b\x32\x38.openconfig.SonicPortchannel.Portchannel.PortchannelListB\x17\n\x15\x63om.nocsys.openconfigb\x06proto3'
  ,
  dependencies=[ywrapper__pb2.DESCRIPTOR,yext__pb2.DESCRIPTOR,sonic__acl__enums__pb2.DESCRIPTOR,])




_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST = _descriptor.Descriptor(
  name='PortchannelList',
  full_name='openconfig.SonicPortchannel.Portchannel.PortchannelList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='admin_status', full_name='openconfig.SonicPortchannel.Portchannel.PortchannelList.admin_status', index=0,
      number=289246861, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A</sonic-portchannel/portchannel/portchannel-list/admin-status', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='openconfig.SonicPortchannel.Portchannel.PortchannelList.description', index=1,
      number=489610797, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A;/sonic-portchannel/portchannel/portchannel-list/description', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='members', full_name='openconfig.SonicPortchannel.Portchannel.PortchannelList.members', index=2,
      number=390606290, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A7/sonic-portchannel/portchannel/portchannel-list/members', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_links', full_name='openconfig.SonicPortchannel.Portchannel.PortchannelList.min_links', index=3,
      number=106858059, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A9/sonic-portchannel/portchannel/portchannel-list/min-links', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mtu', full_name='openconfig.SonicPortchannel.Portchannel.PortchannelList.mtu', index=4,
      number=527911279, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A3/sonic-portchannel/portchannel/portchannel-list/mtu', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=937,
)

_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLISTKEY = _descriptor.Descriptor(
  name='PortchannelListKey',
  full_name='openconfig.SonicPortchannel.Portchannel.PortchannelListKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portchannel_name', full_name='openconfig.SonicPortchannel.Portchannel.PortchannelListKey.portchannel_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A@/sonic-portchannel/portchannel/portchannel-list/portchannel-name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='portchannel_list', full_name='openconfig.SonicPortchannel.Portchannel.PortchannelListKey.portchannel_list', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=940,
  serialized_end=1139,
)

_SONICPORTCHANNEL_PORTCHANNEL = _descriptor.Descriptor(
  name='Portchannel',
  full_name='openconfig.SonicPortchannel.Portchannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portchannel_list', full_name='openconfig.SonicPortchannel.Portchannel.portchannel_list', index=0,
      number=118674730, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A//sonic-portchannel/portchannel/portchannel-list', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST, _SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLISTKEY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=1139,
)

_SONICPORTCHANNEL = _descriptor.Descriptor(
  name='SonicPortchannel',
  full_name='openconfig.SonicPortchannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portchannel', full_name='openconfig.SonicPortchannel.portchannel', index=0,
      number=36582390, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A\036/sonic-portchannel/portchannel', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SONICPORTCHANNEL_PORTCHANNEL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=1139,
)

_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.fields_by_name['admin_status'].enum_type = sonic__acl__enums__pb2._SONICPORTCHANNELADMINSTATUS
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.fields_by_name['description'].message_type = ywrapper__pb2._STRINGVALUE
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.fields_by_name['members'].message_type = ywrapper__pb2._STRINGVALUE
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.fields_by_name['min_links'].message_type = ywrapper__pb2._UINTVALUE
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.fields_by_name['mtu'].message_type = ywrapper__pb2._UINTVALUE
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.containing_type = _SONICPORTCHANNEL_PORTCHANNEL
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLISTKEY.fields_by_name['portchannel_list'].message_type = _SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLISTKEY.containing_type = _SONICPORTCHANNEL_PORTCHANNEL
_SONICPORTCHANNEL_PORTCHANNEL.fields_by_name['portchannel_list'].message_type = _SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLISTKEY
_SONICPORTCHANNEL_PORTCHANNEL.containing_type = _SONICPORTCHANNEL
_SONICPORTCHANNEL.fields_by_name['portchannel'].message_type = _SONICPORTCHANNEL_PORTCHANNEL
DESCRIPTOR.message_types_by_name['SonicPortchannel'] = _SONICPORTCHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SonicPortchannel = _reflection.GeneratedProtocolMessageType('SonicPortchannel', (_message.Message,), {

  'Portchannel' : _reflection.GeneratedProtocolMessageType('Portchannel', (_message.Message,), {

    'PortchannelList' : _reflection.GeneratedProtocolMessageType('PortchannelList', (_message.Message,), {
      'DESCRIPTOR' : _SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST,
      '__module__' : 'sonic_portchannel_pb2'
      # @@protoc_insertion_point(class_scope:openconfig.SonicPortchannel.Portchannel.PortchannelList)
      })
    ,

    'PortchannelListKey' : _reflection.GeneratedProtocolMessageType('PortchannelListKey', (_message.Message,), {
      'DESCRIPTOR' : _SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLISTKEY,
      '__module__' : 'sonic_portchannel_pb2'
      # @@protoc_insertion_point(class_scope:openconfig.SonicPortchannel.Portchannel.PortchannelListKey)
      })
    ,
    'DESCRIPTOR' : _SONICPORTCHANNEL_PORTCHANNEL,
    '__module__' : 'sonic_portchannel_pb2'
    # @@protoc_insertion_point(class_scope:openconfig.SonicPortchannel.Portchannel)
    })
  ,
  'DESCRIPTOR' : _SONICPORTCHANNEL,
  '__module__' : 'sonic_portchannel_pb2'
  # @@protoc_insertion_point(class_scope:openconfig.SonicPortchannel)
  })
_sym_db.RegisterMessage(SonicPortchannel)
_sym_db.RegisterMessage(SonicPortchannel.Portchannel)
_sym_db.RegisterMessage(SonicPortchannel.Portchannel.PortchannelList)
_sym_db.RegisterMessage(SonicPortchannel.Portchannel.PortchannelListKey)


DESCRIPTOR._options = None
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.fields_by_name['admin_status']._options = None
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.fields_by_name['description']._options = None
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.fields_by_name['members']._options = None
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.fields_by_name['min_links']._options = None
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLIST.fields_by_name['mtu']._options = None
_SONICPORTCHANNEL_PORTCHANNEL_PORTCHANNELLISTKEY.fields_by_name['portchannel_name']._options = None
_SONICPORTCHANNEL_PORTCHANNEL.fields_by_name['portchannel_list']._options = None
_SONICPORTCHANNEL.fields_by_name['portchannel']._options = None
# @@protoc_insertion_point(module_scope)
