# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sonic_port.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ywrapper_pb2 as ywrapper__pb2
import yext_pb2 as yext__pb2
import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sonic_port.proto',
  package='openconfig',
  syntax='proto3',
  serialized_options=b'\n\025com.nocsys.openconfig',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10sonic_port.proto\x12\nopenconfig\x1a\x0eywrapper.proto\x1a\nyext.proto\x1a\x0b\x65nums.proto\"\xd1\x07\n\tSonicPort\x12\x41\n\x04port\x18\xfb\xb6\xa2\xea\x01 \x01(\x0b\x32\x1a.openconfig.SonicPort.PortB\x13\x82\x41\x10/sonic-port/port\x1a\x80\x07\n\x04Port\x12[\n\tport_list\x18\xe0\xcd\xee` \x03(\x0b\x32&.openconfig.SonicPort.Port.PortListKeyB\x1d\x82\x41\x1a/sonic-port/port/port-list\x1a\x96\x05\n\x08PortList\x12\x65\n\x0c\x61\x64min_status\x18\xe7\xb8\xaa\x61 \x01(\x0e\x32 .openconfig.SonicPortAdminStatusB*\x82\x41\'/sonic-port/port/port-list/admin-status\x12M\n\x05\x61lias\x18\xe5\x92\x94\xd7\x01 \x01(\x0b\x32\x15.ywrapper.StringValueB#\x82\x41 /sonic-port/port/port-list/alias\x12Y\n\x0b\x64\x65scription\x18\xab\xac\xcc\xb1\x01 \x01(\x0b\x32\x15.ywrapper.StringValueB)\x82\x41&/sonic-port/port/port-list/description\x12I\n\x03\x66\x65\x63\x18\xef\xed\xf9\xa7\x01 \x01(\x0b\x32\x15.ywrapper.StringValueB!\x82\x41\x1e/sonic-port/port/port-list/fec\x12K\n\x05index\x18\xb1\x9b\xf5\x85\x01 \x01(\x0b\x32\x13.ywrapper.UintValueB#\x82\x41 /sonic-port/port/port-list/index\x12M\n\x05lanes\x18\xf4\x8b\xea\xb4\x01 \x01(\x0b\x32\x15.ywrapper.StringValueB#\x82\x41 /sonic-port/port/port-list/lanes\x12\x46\n\x03mtu\x18\xd9\xef\x8a\x1f \x01(\x0b\x32\x13.ywrapper.UintValueB!\x82\x41\x1e/sonic-port/port/port-list/mtu\x12J\n\x05speed\x18\xf8\xf0\xd6\x35 \x01(\x0b\x32\x13.ywrapper.UintValueB#\x82\x41 /sonic-port/port/port-list/speed\x1a\x81\x01\n\x0bPortListKey\x12:\n\tport_name\x18\x01 \x01(\tB\'\x82\x41$/sonic-port/port/port-list/port-name\x12\x36\n\tport_list\x18\x02 \x01(\x0b\x32#.openconfig.SonicPort.Port.PortListB\x17\n\x15\x63om.nocsys.openconfigb\x06proto3'
  ,
  dependencies=[ywrapper__pb2.DESCRIPTOR,yext__pb2.DESCRIPTOR,enums__pb2.DESCRIPTOR,])




_SONICPORT_PORT_PORTLIST = _descriptor.Descriptor(
  name='PortList',
  full_name='openconfig.SonicPort.Port.PortList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='admin_status', full_name='openconfig.SonicPort.Port.PortList.admin_status', index=0,
      number=204119143, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A\'/sonic-port/port/port-list/admin-status', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alias', full_name='openconfig.SonicPort.Port.PortList.alias', index=1,
      number=451217765, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A /sonic-port/port/port-list/alias', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='openconfig.SonicPort.Port.PortList.description', index=2,
      number=372446763, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A&/sonic-port/port/port-list/description', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fec', full_name='openconfig.SonicPort.Port.PortList.fec', index=3,
      number=352220911, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A\036/sonic-port/port/port-list/fec', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='openconfig.SonicPort.Port.PortList.index', index=4,
      number=280841649, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A /sonic-port/port/port-list/index', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lanes', full_name='openconfig.SonicPort.Port.PortList.lanes', index=5,
      number=379225588, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A /sonic-port/port/port-list/lanes', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mtu', full_name='openconfig.SonicPort.Port.PortList.mtu', index=6,
      number=65189849, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A\036/sonic-port/port/port-list/mtu', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='openconfig.SonicPort.Port.PortList.speed', index=7,
      number=112572536, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A /sonic-port/port/port-list/speed', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=919,
)

_SONICPORT_PORT_PORTLISTKEY = _descriptor.Descriptor(
  name='PortListKey',
  full_name='openconfig.SonicPort.Port.PortListKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='port_name', full_name='openconfig.SonicPort.Port.PortListKey.port_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A$/sonic-port/port/port-list/port-name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port_list', full_name='openconfig.SonicPort.Port.PortListKey.port_list', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=922,
  serialized_end=1051,
)

_SONICPORT_PORT = _descriptor.Descriptor(
  name='Port',
  full_name='openconfig.SonicPort.Port',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='port_list', full_name='openconfig.SonicPort.Port.port_list', index=0,
      number=203138784, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A\032/sonic-port/port/port-list', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SONICPORT_PORT_PORTLIST, _SONICPORT_PORT_PORTLISTKEY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=1051,
)

_SONICPORT = _descriptor.Descriptor(
  name='SonicPort',
  full_name='openconfig.SonicPort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='openconfig.SonicPort.port', index=0,
      number=491297659, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202A\020/sonic-port/port', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SONICPORT_PORT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=1051,
)

_SONICPORT_PORT_PORTLIST.fields_by_name['admin_status'].enum_type = enums__pb2._SONICPORTADMINSTATUS
_SONICPORT_PORT_PORTLIST.fields_by_name['alias'].message_type = ywrapper__pb2._STRINGVALUE
_SONICPORT_PORT_PORTLIST.fields_by_name['description'].message_type = ywrapper__pb2._STRINGVALUE
_SONICPORT_PORT_PORTLIST.fields_by_name['fec'].message_type = ywrapper__pb2._STRINGVALUE
_SONICPORT_PORT_PORTLIST.fields_by_name['index'].message_type = ywrapper__pb2._UINTVALUE
_SONICPORT_PORT_PORTLIST.fields_by_name['lanes'].message_type = ywrapper__pb2._STRINGVALUE
_SONICPORT_PORT_PORTLIST.fields_by_name['mtu'].message_type = ywrapper__pb2._UINTVALUE
_SONICPORT_PORT_PORTLIST.fields_by_name['speed'].message_type = ywrapper__pb2._UINTVALUE
_SONICPORT_PORT_PORTLIST.containing_type = _SONICPORT_PORT
_SONICPORT_PORT_PORTLISTKEY.fields_by_name['port_list'].message_type = _SONICPORT_PORT_PORTLIST
_SONICPORT_PORT_PORTLISTKEY.containing_type = _SONICPORT_PORT
_SONICPORT_PORT.fields_by_name['port_list'].message_type = _SONICPORT_PORT_PORTLISTKEY
_SONICPORT_PORT.containing_type = _SONICPORT
_SONICPORT.fields_by_name['port'].message_type = _SONICPORT_PORT
DESCRIPTOR.message_types_by_name['SonicPort'] = _SONICPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SonicPort = _reflection.GeneratedProtocolMessageType('SonicPort', (_message.Message,), {

  'Port' : _reflection.GeneratedProtocolMessageType('Port', (_message.Message,), {

    'PortList' : _reflection.GeneratedProtocolMessageType('PortList', (_message.Message,), {
      'DESCRIPTOR' : _SONICPORT_PORT_PORTLIST,
      '__module__' : 'sonic_port_pb2'
      # @@protoc_insertion_point(class_scope:openconfig.SonicPort.Port.PortList)
      })
    ,

    'PortListKey' : _reflection.GeneratedProtocolMessageType('PortListKey', (_message.Message,), {
      'DESCRIPTOR' : _SONICPORT_PORT_PORTLISTKEY,
      '__module__' : 'sonic_port_pb2'
      # @@protoc_insertion_point(class_scope:openconfig.SonicPort.Port.PortListKey)
      })
    ,
    'DESCRIPTOR' : _SONICPORT_PORT,
    '__module__' : 'sonic_port_pb2'
    # @@protoc_insertion_point(class_scope:openconfig.SonicPort.Port)
    })
  ,
  'DESCRIPTOR' : _SONICPORT,
  '__module__' : 'sonic_port_pb2'
  # @@protoc_insertion_point(class_scope:openconfig.SonicPort)
  })
_sym_db.RegisterMessage(SonicPort)
_sym_db.RegisterMessage(SonicPort.Port)
_sym_db.RegisterMessage(SonicPort.Port.PortList)
_sym_db.RegisterMessage(SonicPort.Port.PortListKey)


DESCRIPTOR._options = None
_SONICPORT_PORT_PORTLIST.fields_by_name['admin_status']._options = None
_SONICPORT_PORT_PORTLIST.fields_by_name['alias']._options = None
_SONICPORT_PORT_PORTLIST.fields_by_name['description']._options = None
_SONICPORT_PORT_PORTLIST.fields_by_name['fec']._options = None
_SONICPORT_PORT_PORTLIST.fields_by_name['index']._options = None
_SONICPORT_PORT_PORTLIST.fields_by_name['lanes']._options = None
_SONICPORT_PORT_PORTLIST.fields_by_name['mtu']._options = None
_SONICPORT_PORT_PORTLIST.fields_by_name['speed']._options = None
_SONICPORT_PORT_PORTLISTKEY.fields_by_name['port_name']._options = None
_SONICPORT_PORT.fields_by_name['port_list']._options = None
_SONICPORT.fields_by_name['port']._options = None
# @@protoc_insertion_point(module_scope)
