# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sonic_vlan_enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ywrapper_pb2 as ywrapper__pb2
import yext_pb2 as yext__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sonic_vlan_enums.proto',
  package='openconfig',
  syntax='proto3',
  serialized_options=b'\n\025com.nocsys.openconfig',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16sonic_vlan_enums.proto\x12\nopenconfig\x1a\x0eywrapper.proto\x1a\nyext.proto*\x82\x01\n\x14SonicPortAdminStatus\x12\x1e\n\x1aSONICPORTADMINSTATUS_UNSET\x10\x00\x12\"\n\x17SONICPORTADMINSTATUS_up\x10\x01\x1a\x05\x82\x41\x02up\x12&\n\x19SONICPORTADMINSTATUS_down\x10\x02\x1a\x07\x82\x41\x04\x64own*\x82\x01\n\x14SonicVlanAdminStatus\x12\x1e\n\x1aSONICVLANADMINSTATUS_UNSET\x10\x00\x12\"\n\x17SONICVLANADMINSTATUS_up\x10\x01\x1a\x05\x82\x41\x02up\x12&\n\x19SONICVLANADMINSTATUS_down\x10\x02\x1a\x07\x82\x41\x04\x64own*z\n\x11SonicVlanIpFamily\x12\x1b\n\x17SONICVLANIPFAMILY_UNSET\x10\x00\x12#\n\x16SONICVLANIPFAMILY_IPv4\x10\x01\x1a\x07\x82\x41\x04IPv4\x12#\n\x16SONICVLANIPFAMILY_IPv6\x10\x02\x1a\x07\x82\x41\x04IPv6*\xe4\x01\n\x18SonicVlanVlanTaggingMode\x12\"\n\x1eSONICVLANVLANTAGGINGMODE_UNSET\x10\x00\x12.\n\x1fSONICVLANVLANTAGGINGMODE_tagged\x10\x01\x1a\t\x82\x41\x06tagged\x12\x32\n!SONICVLANVLANTAGGINGMODE_untagged\x10\x02\x1a\x0b\x82\x41\x08untagged\x12@\n(SONICVLANVLANTAGGINGMODE_priority_tagged\x10\x03\x1a\x12\x82\x41\x0fpriority_taggedB\x17\n\x15\x63om.nocsys.openconfigb\x06proto3'
  ,
  dependencies=[ywrapper__pb2.DESCRIPTOR,yext__pb2.DESCRIPTOR,])

_SONICPORTADMINSTATUS = _descriptor.EnumDescriptor(
  name='SonicPortAdminStatus',
  full_name='openconfig.SonicPortAdminStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SONICPORTADMINSTATUS_UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICPORTADMINSTATUS_up', index=1, number=1,
      serialized_options=b'\202A\002up',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICPORTADMINSTATUS_down', index=2, number=2,
      serialized_options=b'\202A\004down',
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=67,
  serialized_end=197,
)
_sym_db.RegisterEnumDescriptor(_SONICPORTADMINSTATUS)

SonicPortAdminStatus = enum_type_wrapper.EnumTypeWrapper(_SONICPORTADMINSTATUS)
_SONICVLANADMINSTATUS = _descriptor.EnumDescriptor(
  name='SonicVlanAdminStatus',
  full_name='openconfig.SonicVlanAdminStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SONICVLANADMINSTATUS_UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICVLANADMINSTATUS_up', index=1, number=1,
      serialized_options=b'\202A\002up',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICVLANADMINSTATUS_down', index=2, number=2,
      serialized_options=b'\202A\004down',
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=200,
  serialized_end=330,
)
_sym_db.RegisterEnumDescriptor(_SONICVLANADMINSTATUS)

SonicVlanAdminStatus = enum_type_wrapper.EnumTypeWrapper(_SONICVLANADMINSTATUS)
_SONICVLANIPFAMILY = _descriptor.EnumDescriptor(
  name='SonicVlanIpFamily',
  full_name='openconfig.SonicVlanIpFamily',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SONICVLANIPFAMILY_UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICVLANIPFAMILY_IPv4', index=1, number=1,
      serialized_options=b'\202A\004IPv4',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICVLANIPFAMILY_IPv6', index=2, number=2,
      serialized_options=b'\202A\004IPv6',
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=332,
  serialized_end=454,
)
_sym_db.RegisterEnumDescriptor(_SONICVLANIPFAMILY)

SonicVlanIpFamily = enum_type_wrapper.EnumTypeWrapper(_SONICVLANIPFAMILY)
_SONICVLANVLANTAGGINGMODE = _descriptor.EnumDescriptor(
  name='SonicVlanVlanTaggingMode',
  full_name='openconfig.SonicVlanVlanTaggingMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SONICVLANVLANTAGGINGMODE_UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICVLANVLANTAGGINGMODE_tagged', index=1, number=1,
      serialized_options=b'\202A\006tagged',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICVLANVLANTAGGINGMODE_untagged', index=2, number=2,
      serialized_options=b'\202A\010untagged',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SONICVLANVLANTAGGINGMODE_priority_tagged', index=3, number=3,
      serialized_options=b'\202A\017priority_tagged',
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=457,
  serialized_end=685,
)
_sym_db.RegisterEnumDescriptor(_SONICVLANVLANTAGGINGMODE)

SonicVlanVlanTaggingMode = enum_type_wrapper.EnumTypeWrapper(_SONICVLANVLANTAGGINGMODE)
SONICPORTADMINSTATUS_UNSET = 0
SONICPORTADMINSTATUS_up = 1
SONICPORTADMINSTATUS_down = 2
SONICVLANADMINSTATUS_UNSET = 0
SONICVLANADMINSTATUS_up = 1
SONICVLANADMINSTATUS_down = 2
SONICVLANIPFAMILY_UNSET = 0
SONICVLANIPFAMILY_IPv4 = 1
SONICVLANIPFAMILY_IPv6 = 2
SONICVLANVLANTAGGINGMODE_UNSET = 0
SONICVLANVLANTAGGINGMODE_tagged = 1
SONICVLANVLANTAGGINGMODE_untagged = 2
SONICVLANVLANTAGGINGMODE_priority_tagged = 3


DESCRIPTOR.enum_types_by_name['SonicPortAdminStatus'] = _SONICPORTADMINSTATUS
DESCRIPTOR.enum_types_by_name['SonicVlanAdminStatus'] = _SONICVLANADMINSTATUS
DESCRIPTOR.enum_types_by_name['SonicVlanIpFamily'] = _SONICVLANIPFAMILY
DESCRIPTOR.enum_types_by_name['SonicVlanVlanTaggingMode'] = _SONICVLANVLANTAGGINGMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
_SONICPORTADMINSTATUS.values_by_name["SONICPORTADMINSTATUS_up"]._options = None
_SONICPORTADMINSTATUS.values_by_name["SONICPORTADMINSTATUS_down"]._options = None
_SONICVLANADMINSTATUS.values_by_name["SONICVLANADMINSTATUS_up"]._options = None
_SONICVLANADMINSTATUS.values_by_name["SONICVLANADMINSTATUS_down"]._options = None
_SONICVLANIPFAMILY.values_by_name["SONICVLANIPFAMILY_IPv4"]._options = None
_SONICVLANIPFAMILY.values_by_name["SONICVLANIPFAMILY_IPv6"]._options = None
_SONICVLANVLANTAGGINGMODE.values_by_name["SONICVLANVLANTAGGINGMODE_tagged"]._options = None
_SONICVLANVLANTAGGINGMODE.values_by_name["SONICVLANVLANTAGGINGMODE_untagged"]._options = None
_SONICVLANVLANTAGGINGMODE.values_by_name["SONICVLANVLANTAGGINGMODE_priority_tagged"]._options = None
# @@protoc_insertion_point(module_scope)
